version: "3.8"

services:
  web:
    build: .
    container_name: django_app
    expose:
      - "8080" 
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/static 

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro

volumes:
  postgres_data: {}
  static_volume: {}
