# Generated by Django 5.2 on 2025-04-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf', models.CharField(help_text='Digite somente os números do CPF', max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('num_telefone', models.CharField(blank=True, help_text='Número de telefone', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('cpf', models.CharField(help_text='Digite somente os números do CPF', max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('num_telefone', models.CharField(blank=True, help_text='Número de telefone', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscalaPoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('somaTensao', models.IntegerField()),
                ('somaDepressao', models.IntegerField()),
                ('somaHostilidade', models.IntegerField()),
                ('somaFadiga', models.IntegerField()),
                ('somaConfusao', models.IntegerField()),
                ('somaVigor', models.IntegerField()),
                ('somaDesajuste', models.IntegerField()),
                ('pth', models.IntegerField()),
                ('sono', models.IntegerField(blank=True, help_text='Horas de sono', null=True)),
                ('volume_treino', models.IntegerField(blank=True, help_text='Volume de treino (ex: carga, repetições ou outro critério)', null=True)),
                ('freq_cardiaca_media', models.IntegerField(blank=True, help_text='Frequência cardíaca média (BPM)', null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='EscalaPoms.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='treinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='EscalaPoms.treinador'),
        ),
    ]
