# Generated by Django 5.2 on 2025-05-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf', models.CharField(help_text='…', max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=12)),
                ('num_telefone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('cpf', models.CharField(help_text='…', max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=12)),
                ('num_telefone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscalaPoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('soma_tensao', models.IntegerField()),
                ('soma_depressao', models.IntegerField()),
                ('soma_hostilidade', models.IntegerField()),
                ('soma_fadiga', models.IntegerField()),
                ('soma_confusao', models.IntegerField()),
                ('soma_vigor', models.IntegerField()),
                ('soma_desajuste', models.IntegerField()),
                ('pth', models.IntegerField()),
                ('sono', models.IntegerField(blank=True, help_text='Horas de sono', null=True)),
                ('volume_treino', models.IntegerField(blank=True, help_text='Volume de treino (ex: carga, repetições ou outro critério)', null=True)),
                ('freq_cardiaca_media', models.IntegerField(blank=True, help_text='Frequência cardíaca média (BPM)', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Informações complementares (ex: tomando remédio, acontecimentos da semana)', null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='EscalaPoms.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_tensao', models.CharField(max_length=20)),
                ('nivel_depressao', models.CharField(max_length=20)),
                ('nivel_hostilidade', models.CharField(max_length=20)),
                ('nivel_fadiga', models.CharField(max_length=20)),
                ('nivel_confusao', models.CharField(max_length=20)),
                ('nivel_vigor', models.CharField(max_length=20)),
                ('nivel_desajuste', models.CharField(max_length=20)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='EscalaPoms.escalapoms')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='treinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='EscalaPoms.treinador'),
        ),
    ]
