# Generated by Django 5.2 on 2025-05-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=12),
        ),
        migrations.AlterField(
            model_name='treinador',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=12),
        ),
    ]
