# Generated by Django 5.2 on 2025-05-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(help_text='…', max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escalapoms',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='treinador',
            name='cpf',
            field=models.CharField(help_text='…', max_length=14, primary_key=True, serialize=False),
        ),
    ]
