# Generated by Django 5.2 on 2025-05-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0002_alter_aluno_genero_alter_treinador_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escalapoms',
            old_name='somaConfusao',
            new_name='soma_confusao',
        ),
        migrations.RenameField(
            model_name='escalapoms',
            old_name='somaDepressao',
            new_name='soma_depressao',
        ),
        migrations.RenameField(
            model_name='escalapoms',
            old_name='somaDesajuste',
            new_name='soma_desajuste',
        ),
        migrations.RenameField(
            model_name='escalapoms',
            old_name='somaFadiga',
            new_name='soma_fadiga',
        ),
        migrations.RenameField(
            model_name='escalapoms',
            old_name='somaHostilidade',
            new_name='soma_hostilidade',
        ),
        migrations.RenameField(
            model_name='escalapoms',
            old_name='somaTensao',
            new_name='soma_tensao',
        ),
        migrations.RenameField(
            model_name='escalapoms',
            old_name='somaVigor',
            new_name='soma_vigor',
        ),
    ]
