# Generated by Django 5.2 on 2025-05-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0002_alter_aluno_cpf_alter_escalapoms_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treinador',
            name='cpf',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
