# Generated by Django 5.2 on 2025-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0002_aluno_foto_treinador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treinador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
