# Generated by Django 5.2 on 2025-05-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0003_rename_somaconfusao_escalapoms_soma_confusao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_tensao', models.CharField(max_length=20)),
                ('nivel_depressao', models.CharField(max_length=20)),
                ('nivel_hostilidade', models.CharField(max_length=20)),
                ('nivel_fadiga', models.CharField(max_length=20)),
                ('nivel_confusao', models.CharField(max_length=20)),
                ('nivel_vigor', models.CharField(max_length=20)),
                ('nivel_desajuste', models.CharField(max_length=20)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='EscalaPoms.escalapoms')),
            ],
        ),
    ]
