# Generated by Django 5.2 on 2025-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0003_alter_aluno_cpf_alter_treinador_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalapoms',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
