# Generated by Django 5.2 on 2025-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0004_classificacaorecomendacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalapoms',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Informações complementares (ex: tomando remédio, acontecimentos da semana)', null=True),
        ),
    ]
