# Generated by Django 5.2 on 2025-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscalaPoms', '0004_escalapoms_enviado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificacaorecomendacao',
            old_name='recomendacao',
            new_name='sugestao_treino_confusao',
        ),
        migrations.AddField(
            model_name='classificacaorecomendacao',
            name='sugestao_treino_depressao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificacaorecomendacao',
            name='sugestao_treino_fadiga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificacaorecomendacao',
            name='sugestao_treino_hostilidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificacaorecomendacao',
            name='sugestao_treino_tensao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classificacaorecomendacao',
            name='sugestao_treino_vigor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
